import { Injectable } from '@angular/core';

import { Livro } from '../models/livro';

@Injectable({
  providedIn: 'root'
})
export class LivroService {

  private readonly livros: readonly Livro[] = [
    {
      id: 1,
      titulo: 'Harry Potter e a Pedra Filosofal',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Harry Potter e a Pedra Filosofal acompanha um garoto órfão que descobre ser um bruxo aos 11 anos.',
      dataPublicacao: new Date(1997, 5, 26),
      paginas: 264,
      capaUrl: 'livros/harry-potterPF.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 2,
      titulo: 'Harry Potter e a Câmara Secreta',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Em seu segundo ano em Hogwarts, Harry precisa encontrar e fechar a lendária Câmara Secreta após um monstro começar a petrificar alunos.',
      dataPublicacao: new Date(1998, 6, 2),
      capaUrl: 'livros/harry-potterCS.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 3,
      titulo: 'Harry Potter e o Prisioneiro de Azkaban',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Harry descobre segredos do passado de seus pais enquanto a escola é cercada por Dementadores devido à fuga do prisioneiro Sirius Black.',
      dataPublicacao: new Date(1999, 6, 8),
      capaUrl: 'livros/harry-potterPA.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 4,
      titulo: 'Harry Potter e o Cálice de Fogo',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Selecionado misteriosamente para o perigoso Torneio Tribruxo, Harry enfrenta tarefas mortais em um plano para trazer Voldemort de volta.',
      dataPublicacao: new Date(2000, 6, 8),
      capaUrl: 'livros/harry-potterCF.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 5,
      titulo: 'Harry Potter e a Ordem da Fênix',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Com o Ministério da Magia negando o retorno de Voldemort, Harry lidera secretamente um grupo de alunos para se defenderem das trevas.',
      dataPublicacao: new Date(2003, 5, 21),
      capaUrl: 'livros/harry-potterOF.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 6,
      titulo: 'Harry Potter e o Enigma do Príncipe',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Harry encontra um antigo livro misterioso e tem lições com Dumbledore para descobrir as origens de Voldemort e o segredo das Horcruxes.',
      dataPublicacao: new Date(2005, 6, 16),
      capaUrl: 'livros/harry-potterEP.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 7,
      titulo: 'Harry Potter e as Relíquias da Morte',
      autor: 'J.K. Rowling',
      subtitulo: '',
      descricao: 'Harry, Rony e Hermione abandonam a escola para caçar as Horcruxes restantes, culminando na batalha final contra Voldemort.',
      dataPublicacao: new Date(2007, 6, 21),
      capaUrl: 'livros/harry-potterRM.jpg',
      idioma: 'Português',
      colecaoId: 1,
      status: 'disponível'
    },
    {
      id: 8,
      titulo: 'O Senhor dos Anéis: A Sociedade do Anel',
      autor: 'J.R.R. Tolkien',
      subtitulo: '',
      descricao: 'Frodo Bolseiro herda um anel misterioso e descobre que ele é a arma do Senhor do Escuro. Ao lado de uma Sociedade de nove companheiros, começa a jornada rumo à Montanha da Perdição para destruí-lo.',
      dataPublicacao: new Date(1954, 6, 29),
      capaUrl: 'livros/SociedadeDoAnel.jpg',
      idioma: 'Português',
      colecaoId: 2,
      status: 'disponível'
    },
    {
      id: 9,
      titulo: 'O Senhor dos Anéis: As Duas Torres',
      autor: 'J.R.R. Tolkien',
      subtitulo: '',
      descricao: 'A Sociedade se desfaz: Frodo e Sam seguem para Mordor guiados por Gollum, enquanto Aragorn, Legolas e Gimli lutam para defender Rohan da ameaça de Saruman.',
      dataPublicacao: new Date(1954, 10, 11),
      capaUrl: 'livros/AsDuasTorres.jpg',
      idioma: 'Português',
      colecaoId: 2,
      status: 'disponível'
    },
    {
      id: 10,
      titulo: 'O Senhor dos Anéis: O Retorno do Rei',
      autor: 'J.R.R. Tolkien',
      subtitulo: '',
      descricao: 'Com os exércitos de Sauron reunidos, Gondor enfrenta a batalha decisiva enquanto Frodo e Sam tentam alcançar a Montanha da Perdição. O destino da Terra-média está em jogo.',
      dataPublicacao: new Date(1955, 9, 20),
      capaUrl: 'livros/oRetornoDoRei.jpg',
      idioma: 'Português',
      colecaoId: 2,
      status: 'disponível'
    },
    {
      id: 11,
      titulo: 'Para Todos os Garotos Que Já Amei',
      autor: 'Jenny Han',
      subtitulo: '',
      descricao: 'Lara Jean guarda suas cartas de amor secretas em uma caixa de chapéu, até que elas são enviadas misteriosamente aos garotos por quem já se apaixonou e sua vida vira de cabeça para baixo.',
      dataPublicacao: new Date(2014, 3, 15),
      capaUrl: 'livros/PTGA.jpg',
      idioma: 'Português',
      colecaoId: 3,
      status: 'disponível'
    },
    {
      id: 12,
      titulo: 'P.S. Ainda Amo Você',
      autor: 'Jenny Han',
      subtitulo: '',
      descricao: 'Lara Jean e Peter tentam transformar um namoro de mentira em algo real, mas a volta de um antigo destinatário de suas cartas a deixa dividida.',
      dataPublicacao: new Date(2015, 4, 26),
      capaUrl: 'livros/AAC.jpg',
      idioma: 'Português',
      colecaoId: 3,
      status: 'disponível'
    },
    {
      id: 13,
      titulo: 'Sempre e Para Sempre, Lara Jean',
      autor: 'Jenny Han',
      subtitulo: '',
      descricao: 'No último ano do ensino médio, Lara Jean precisa lidar com a escolha da faculdade, o casamento do pai e o futuro do namoro com Peter, enquanto se despede de uma fase da vida.',
      dataPublicacao: new Date(2017, 4, 2),
      capaUrl: 'livros/Sempre.jpg',
      idioma: 'Português',
      colecaoId: 3,
      status: 'disponível'
    },
    {
      id: 14,
      titulo: 'Mistborn: O Império Final',
      autor: 'Brandon Sanderson',
      subtitulo: '',
      descricao: 'Em um mundo coberto de cinzas e dominado há mil anos por um Lorde Soberano imortal, a jovem ladra Vin descobre ser uma Névoa e se une a uma gangue que planeja derrubar o império.',
      dataPublicacao: new Date(2006, 6, 17),
      capaUrl: 'livros/mist1.jpg',
      idioma: 'Português',
      colecaoId: 4,
      status: 'disponível'
    },
    {
      id: 15,
      titulo: 'Mistborn: O Poço da Ascensão',
      autor: 'Brandon Sanderson',
      subtitulo: '',
      descricao: 'Com o Império Final derrubado, Vin e Elend tentam manter a cidade de Luthadel unida enquanto exércitos rivais cercam seus muros e novos mistérios sobre o passado do mundo vêm à tona.',
      dataPublicacao: new Date(2007, 7, 21),
      capaUrl: 'livros/mist2.jpg',
      idioma: 'Português',
      colecaoId: 4,
      status: 'disponível'
    },
    {
      id: 16,
      titulo: 'Mistborn: O Herói das Eras',
      autor: 'Brandon Sanderson',
      subtitulo: '',
      descricao: 'A névoa fica cada vez mais mortal e o mundo se desfaz. Vin e Elend precisam desvendar o segredo da Ascensão para salvar o que resta da humanidade.',
      dataPublicacao: new Date(2008, 9, 14),
      capaUrl: 'livros/mist3.jpg',
      idioma: 'Português',
      colecaoId: 4,
      status: 'disponível'
    },
    {
      id: 17,
      titulo: 'Jogos Vorazes',
      autor: 'Suzanne Collins',
      subtitulo: '',
      descricao: 'Em uma nação futurista que obriga jovens a lutarem até a morte em um programa de TV, Katniss Everdeen se oferece no lugar da irmã e precisa sobreviver à arena.',
      dataPublicacao: new Date(2008, 8, 14),
      capaUrl: 'livros/jv1.jpg',
      idioma: 'Português',
      colecaoId: 5,
      status: 'disponível'
    },
    {
      id: 18,
      titulo: 'Em Chamas',
      autor: 'Suzanne Collins',
      subtitulo: '',
      descricao: 'Após a vitória nos Jogos, Katniss se torna símbolo de esperança para os distritos e passa a ser alvo da Capital, que prepara uma edição ainda mais cruel do torneio.',
      dataPublicacao: new Date(2009, 8, 1),
      capaUrl: 'livros/jv2.jpg',
      idioma: 'Português',
      colecaoId: 5,
      status: 'disponível'
    },
    {
      id: 19,
      titulo: 'A Esperança',
      autor: 'Suzanne Collins',
      subtitulo: '',
      descricao: 'A rebelião contra a Capital chega ao auge, e Katniss precisa decidir até onde irá pelo destino dos distritos e das pessoas que ama.',
      dataPublicacao: new Date(2010, 7, 24),
      capaUrl: 'livros/jv3.jpg',
      idioma: 'Português',
      colecaoId: 5,
      status: 'disponível'
    },
    {
      id: 20,
      titulo: 'A Seleção',
      autor: 'Kiera Cass',
      subtitulo: '',
      descricao: 'Para escapar da vida em uma sociedade de castas, America Singer entra na Seleção, competição que escolherá a futura esposa do príncipe Maxon, mesmo com o coração preso a outro garoto.',
      dataPublicacao: new Date(2012, 3, 24),
      capaUrl: 'livros/sel1.jpg',
      idioma: 'Português',
      colecaoId: 6,
      status: 'disponível'
    },
    {
      id: 21,
      titulo: 'A Elite',
      autor: 'Kiera Cass',
      subtitulo: '',
      descricao: 'Com a disputa reduzida a poucas candidatas, America precisa decidir entre o príncipe e seu passado enquanto os ataques rebeldes ao palácio ficam mais perigosos.',
      dataPublicacao: new Date(2013, 3, 23),
      capaUrl: 'livros/sel2.jpg',
      idioma: 'Português',
      colecaoId: 6,
      status: 'disponível'
    },
    {
      id: 22,
      titulo: 'A Escolha',
      autor: 'Kiera Cass',
      subtitulo: '',
      descricao: 'Na etapa final, o amor, a lealdade e o futuro do reino entram em jogo, e America precisa fazer a escolha que definirá sua vida.',
      dataPublicacao: new Date(2014, 4, 6),
      capaUrl: 'livros/sel3.jpg',
      idioma: 'Português',
      colecaoId: 6,
      status: 'disponível'
    },
    {
      id: 23,
      titulo: 'Sherlock Holmes: Um Estudo em Vermelho',
      autor: 'Arthur Conan Doyle',
      subtitulo: '',
      descricao: 'Primeira aparição de Sherlock Holmes: ao dividir um apartamento com o doutor Watson, o detetive investiga um misterioso assassinato em Londres.',
      dataPublicacao: new Date(1887, 10, 1),
      capaUrl: 'livros/s1.jpg',
      idioma: 'Português',
      colecaoId: 7,
      status: 'disponível'
    },
    {
      id: 24,
      titulo: 'Sherlock Holmes: O Signo dos Quatro',
      autor: 'Arthur Conan Doyle',
      subtitulo: '',
      descricao: 'Uma jovem recebe pérolas misteriosas e procura Holmes. A investigação revela um antigo tesouro e um crime ligado a segredos vindos da Índia.',
      dataPublicacao: new Date(1890, 1, 1),
      capaUrl: 'livros/s2.jpg',
      idioma: 'Português',
      colecaoId: 7,
      status: 'disponível'
    },
    {
      id: 25,
      titulo: 'Sherlock Holmes: O Cão dos Baskervilles',
      autor: 'Arthur Conan Doyle',
      subtitulo: '',
      descricao: 'Holmes e Watson investigam a lenda de um cão espectral que assombra a família Baskerville nos pântanos de Dartmoor.',
      dataPublicacao: new Date(1902, 2, 1),
      capaUrl: 'livros/s3.jpg',
      idioma: 'Português',
      colecaoId: 7,
      status: 'disponível'
    },
    {
      id: 26,
      titulo: 'As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa',
      autor: 'C.S. Lewis',
      subtitulo: '',
      descricao: 'Quatro irmãos atravessam um guarda-roupa e chegam a Nárnia, reino enfeitiçado por um inverno sem fim, onde o leão Aslam é a esperança de libertação.',
      dataPublicacao: new Date(1950, 9, 16),
      capaUrl: 'livros/narnia1.jpg',
      idioma: 'Português',
      colecaoId: 8,
      status: 'disponível'
    },
    {
      id: 27,
      titulo: 'As Crônicas de Nárnia: Príncipe Caspian',
      autor: 'C.S. Lewis',
      subtitulo: '',
      descricao: 'Os irmãos Pevensie voltam a uma Nárnia muito mudada para ajudar o jovem príncipe Caspian a recuperar o trono e devolver o reino às criaturas antigas.',
      dataPublicacao: new Date(1951, 9, 15),
      capaUrl: 'livros/narnia2.jpg',
      idioma: 'Português',
      colecaoId: 8,
      status: 'disponível'
    },
    {
      id: 28,
      titulo: 'As Crônicas de Nárnia: O Cavalo e seu Menino',
      autor: 'C.S. Lewis',
      subtitulo: '',
      descricao: 'Shasta, um menino criado em Calormen, foge com o cavalo falante Bree e cruza o deserto para alertar Nárnia e Arquelândia sobre uma invasão iminente.',
      dataPublicacao: new Date(1954, 8, 4),
      capaUrl: 'livros/narnia3.jpg',
      idioma: 'Português',
      colecaoId: 8,
      status: 'disponível'
    },
    {
      id: 29,
      titulo: 'Percy Jackson: O Ladrão de Raios',
      autor: 'Rick Riordan',
      subtitulo: '',
      descricao: 'Percy Jackson descobre que é filho de um deus grego e, acusado de roubar o raio de Zeus, parte em uma missão para evitar uma guerra entre os deuses.',
      dataPublicacao: new Date(2005, 5, 28),
      capaUrl: 'livros/PJLadrao.jpeg',
      idioma: 'Português',
      colecaoId: 9,
      status: 'disponível'
    },
    {
      id: 30,
      titulo: 'Percy Jackson: O Mar de Monstros',
      autor: 'Rick Riordan',
      subtitulo: '',
      descricao: 'Para salvar o acampamento dos semideuses, Percy e seus amigos cruzam o Mar de Monstros em busca do Velocino de Ouro.',
      dataPublicacao: new Date(2006, 3, 1),
      capaUrl: 'livros/PJMarMontros.jpg',
      idioma: 'Português',
      colecaoId: 9,
      status: 'disponível'
    },
    {
      id: 31,
      titulo: 'Percy Jackson: A Maldição do Titã',
      autor: 'Rick Riordan',
      subtitulo: '',
      descricao: 'Percy e seus aliados correm contra o tempo para resgatar Annabeth e a deusa Ártemis, enquanto os titãs ganham força.',
      dataPublicacao: new Date(2007, 4, 1),
      capaUrl: 'livros/PJMaldicao.jpg',
      idioma: 'Português',
      colecaoId: 9,
      status: 'disponível'
    },
    {
      id: 32,
      titulo: 'Crepúsculo',
      autor: 'Stephenie Meyer',
      subtitulo: '',
      descricao: 'Ao se mudar para a chuvosa Forks, Bella Swan se apaixona por Edward Cullen, um rapaz misterioso que guarda um segredo sobre sua família.',
      dataPublicacao: new Date(2005, 9, 5),
      capaUrl: 'livros/Crepusculo.jpg',
      idioma: 'Português',
      colecaoId: 10,
      status: 'disponível'
    },
    {
      id: 33,
      titulo: 'Lua Nova',
      autor: 'Stephenie Meyer',
      subtitulo: '',
      descricao: 'Depois de uma separação dolorosa, Bella se aproxima de Jacob Black e descobre que o mundo sobrenatural de Forks é maior do que imaginava.',
      dataPublicacao: new Date(2006, 8, 6),
      capaUrl: 'livros/Crepusculo2.jpg',
      idioma: 'Português',
      colecaoId: 10,
      status: 'disponível'
    },
    {
      id: 34,
      titulo: 'Eclipse',
      autor: 'Stephenie Meyer',
      subtitulo: '',
      descricao: 'Ameaças crescem ao redor de Forks e Bella precisa lidar com o perigo e com a escolha entre Edward e Jacob antes de decidir seu futuro.',
      dataPublicacao: new Date(2007, 7, 7),
      capaUrl: 'livros/Crepusculo3.jpg',
      idioma: 'Português',
      colecaoId: 10,
      status: 'disponível'
    },
    {
      id: 35,
      titulo: 'Anna e o Beijo Francês',
      autor: 'Stephanie Perkins',
      subtitulo: '',
      descricao: 'Enviada para estudar em Paris, Anna Oliphant precisa se adaptar a um novo país e lida com sentimentos por um colega charmoso e já comprometido.',
      dataPublicacao: new Date(2010, 11, 2),
      capaUrl: 'livros/Anna1.jpg',
      idioma: 'Português',
      colecaoId: 11,
      status: 'disponível'
    },
    {
      id: 36,
      titulo: 'Lola e o Garoto da Casa ao Lado',
      autor: 'Stephanie Perkins',
      subtitulo: '',
      descricao: 'Lola, criadora de fantasias extravagantes, vê a vida virar de cabeça para baixo quando os vizinhos gêmeos, de quem se afastou, voltam para a casa ao lado.',
      dataPublicacao: new Date(2011, 8, 29),
      capaUrl: 'livros/Lola.jpg',
      idioma: 'Português',
      colecaoId: 11,
      status: 'disponível'
    },
    {
      id: 37,
      titulo: 'Isla e o Final Feliz',
      autor: 'Stephanie Perkins',
      subtitulo: '',
      descricao: 'Isla finalmente se aproxima de Josh, o garoto por quem é apaixonada há anos, e os dois vivem um romance posto à prova entre Paris e Nova York.',
      dataPublicacao: new Date(2014, 7, 14),
      capaUrl: 'livros/Isla.jpg',
      idioma: 'Português',
      colecaoId: 11,
      status: 'disponível'
    },
    {
      id: 38,
      titulo: 'Como Eu Era Antes de Você',
      autor: 'Jojo Moyes',
      subtitulo: '',
      descricao: 'Louisa Clark aceita um emprego como cuidadora de Will Traynor, jovem tetraplégico e amargurado, e os dois mudam a vida um do outro.',
      dataPublicacao: new Date(2012, 0, 5),
      capaUrl: 'livros/ComoEuEra.jpg',
      idioma: 'Português',
      colecaoId: 12,
      status: 'disponível'
    },
    {
      id: 39,
      titulo: 'Depois de Você',
      autor: 'Jojo Moyes',
      subtitulo: '',
      descricao: 'Louisa tenta reconstruir a vida depois de uma perda enorme quando uma descoberta inesperada a obriga a encarar o passado.',
      dataPublicacao: new Date(2015, 8, 24),
      capaUrl: 'livros/DepoisDeVoce.jpg',
      idioma: 'Português',
      colecaoId: 12,
      status: 'disponível'
    },
    {
      id: 40,
      titulo: 'Ainda Sou Eu',
      autor: 'Jojo Moyes',
      subtitulo: '',
      descricao: 'Louisa se muda para Nova York e tenta encontrar seu lugar em um mundo novo, entre um trabalho desafiador e as dúvidas sobre o amor.',
      dataPublicacao: new Date(2018, 0, 30),
      capaUrl: 'livros/AindaSouEu.jpg',
      idioma: 'Português',
      colecaoId: 12,
      status: 'disponível'
    },
    {
      id: 41,
      titulo: 'Divergente',
      autor: 'Veronica Roth',
      subtitulo: '',
      descricao: 'Em uma Chicago do futuro dividida em facções, Beatrice descobre ser Divergente, algo perigoso em uma sociedade que exige conformidade.',
      dataPublicacao: new Date(2011, 3, 25),
      capaUrl: 'livros/Divergente.jpg',
      idioma: 'Português',
      colecaoId: 13,
      status: 'disponível'
    },
    {
      id: 42,
      titulo: 'Insurgente',
      autor: 'Veronica Roth',
      subtitulo: '',
      descricao: 'Tris tenta sobreviver ao conflito entre as facções enquanto segredos sobre o sistema e sobre as pessoas ao seu redor vêm à tona.',
      dataPublicacao: new Date(2012, 4, 1),
      capaUrl: 'livros/Insurgente.jpg',
      idioma: 'Português',
      colecaoId: 13,
      status: 'disponível'
    },
    {
      id: 43,
      titulo: 'Convergente',
      autor: 'Veronica Roth',
      subtitulo: '',
      descricao: 'Com a cidade em guerra e as regras abaladas, Tris e Quatro precisam enfrentar a verdade sobre o mundo além dos muros.',
      dataPublicacao: new Date(2013, 9, 22),
      capaUrl: 'livros/Convergente.jpg',
      idioma: 'Português',
      colecaoId: 13,
      status: 'disponível'
    },
    {
      id: 44,
      titulo: 'Maze Runner: Correr ou Morrer',
      autor: 'James Dashner',
      subtitulo: '',
      descricao: 'Thomas acorda sem memória em uma clareira cercada por um labirinto gigante e se junta aos garotos que tentam encontrar a saída.',
      dataPublicacao: new Date(2009, 9, 6),
      capaUrl: 'livros/Maze1.jpg',
      idioma: 'Português',
      colecaoId: 14,
      status: 'disponível'
    },
    {
      id: 45,
      titulo: 'Maze Runner: Prova de Fogo',
      autor: 'James Dashner',
      subtitulo: '',
      descricao: 'Fora do labirinto, Thomas e seus amigos encontram um deserto devastado e novos testes que desafiam a confiança entre eles.',
      dataPublicacao: new Date(2010, 9, 12),
      capaUrl: 'livros/Maze2.jpg',
      idioma: 'Português',
      colecaoId: 14,
      status: 'disponível'
    },
    {
      id: 46,
      titulo: 'Maze Runner: A Cura Mortal',
      autor: 'James Dashner',
      subtitulo: '',
      descricao: 'Em busca da cura para uma doença mortal, Thomas e seus companheiros precisam decidir em quem confiar para sobreviver.',
      dataPublicacao: new Date(2011, 9, 11),
      capaUrl: 'livros/Maze3.jpg',
      idioma: 'Português',
      colecaoId: 14,
      status: 'disponível'
    },
    {
      id: 47,
      titulo: 'Duna',
      autor: 'Frank Herbert',
      subtitulo: '',
      descricao: 'No deserto do planeta Arrakis, único produtor da especiaria mais valiosa do universo, o jovem Paul Atreides se vê no centro de intrigas e de uma guerra por poder.',
      dataPublicacao: new Date(1965, 7, 1),
      capaUrl: 'livros/Duna.jpg',
      idioma: 'Português',
      colecaoId: 15,
      status: 'disponível'
    },
    {
      id: 48,
      titulo: 'Messias de Duna',
      autor: 'Frank Herbert',
      subtitulo: '',
      descricao: 'Anos depois, Paul governa um império galáctico e enfrenta conspirações enquanto lida com o peso de suas visões do futuro.',
      dataPublicacao: new Date(1969, 9, 1),
      capaUrl: 'livros/Duna2.jpg',
      idioma: 'Português',
      colecaoId: 15,
      status: 'disponível'
    },
    {
      id: 49,
      titulo: 'Os Filhos de Duna',
      autor: 'Frank Herbert',
      subtitulo: '',
      descricao: 'Os filhos de Paul crescem em um Arrakis que muda aos poucos, e disputas políticas e religiosas ameaçam o rumo da família Atreides.',
      dataPublicacao: new Date(1976, 3, 1),
      capaUrl: 'livros/Duna3.jpg',
      idioma: 'Português',
      colecaoId: 15,
      status: 'disponível'
    },
    {
      id: 50,
      titulo: 'Fundação',
      autor: 'Isaac Asimov',
      subtitulo: '',
      descricao: 'Com o declínio do Império Galáctico previsto pela psico-história, o matemático Hari Seldon cria a Fundação para reduzir a era de trevas que virá.',
      dataPublicacao: new Date(1951, 4, 1),
      capaUrl: 'livros/Fundacao.jpg',
      idioma: 'Português',
      colecaoId: 16,
      status: 'disponível'
    },
    {
      id: 51,
      titulo: 'Fundação e Império',
      autor: 'Isaac Asimov',
      subtitulo: '',
      descricao: 'A Fundação enfrenta um general poderoso do Império e um misterioso inimigo capaz de controlar mentes.',
      dataPublicacao: new Date(1952, 7, 1),
      capaUrl: 'livros/Fundacao2.jpg',
      idioma: 'Português',
      colecaoId: 16,
      status: 'disponível'
    },
    {
      id: 52,
      titulo: 'Segunda Fundação',
      autor: 'Isaac Asimov',
      subtitulo: '',
      descricao: 'A busca pela misteriosa Segunda Fundação leva a descobrir que o plano de Seldon guarda mais segredos do que se imaginava.',
      dataPublicacao: new Date(1953, 7, 1),
      capaUrl: 'livros/Fundacao3.jpg',
      idioma: 'Português',
      colecaoId: 16,
      status: 'disponível'
    },
    {
      id: 53,
      titulo: 'Hercule Poirot: Os Assassinatos de Kingfisher Hill',
      autor: 'Sophie Hannah',
      subtitulo: '',
      descricao: 'Chamado para provar a inocência de uma mulher acusada de assassinar o noivo do irmão, Poirot viaja de ônibus até a propriedade dos Devonport, onde uma estranha troca de assentos esconde um crime.',
      dataPublicacao: new Date(2020, 7, 20),
      capaUrl: 'livros/Hercule.jpg',
      idioma: 'Português',
      colecaoId: 17,
      status: 'disponível'
    },
    {
      id: 54,
      titulo: 'Hercule Poirot: Assassinato no Expresso do Oriente',
      autor: 'Agatha Christie',
      subtitulo: '',
      descricao: 'Preso pela neve em um luxuoso trem, Poirot investiga o assassinato de um passageiro, cercado de suspeitos com segredos.',
      dataPublicacao: new Date(1934, 0, 1),
      capaUrl: 'livros/Hercule2.jpg',
      idioma: 'Português',
      colecaoId: 17,
      status: 'disponível'
    },
    {
      id: 55,
      titulo: 'Hercule Poirot: Morte no Nilo',
      autor: 'Agatha Christie',
      subtitulo: '',
      descricao: 'Durante um cruzeiro pelo rio Nilo, uma jovem herdeira é assassinada e Poirot precisa descobrir quem, entre os passageiros, tinha motivo.',
      dataPublicacao: new Date(1937, 10, 1),
      capaUrl: 'livros/Hercule3.jpg',
      idioma: 'Português',
      colecaoId: 17,
      status: 'disponível'
    },
    {
      id: 56,
      titulo: 'Robert Langdon: Anjos e Demônios',
      autor: 'Dan Brown',
      subtitulo: '',
      descricao: 'O simbologista Robert Langdon é chamado ao Vaticano para impedir um plano ligado a uma antiga sociedade secreta.',
      dataPublicacao: new Date(2000, 4, 1),
      capaUrl: 'livros/Robert.jpg',
      idioma: 'Português',
      colecaoId: 18,
      status: 'disponível'
    },
    {
      id: 57,
      titulo: 'Robert Langdon: O Código Da Vinci',
      autor: 'Dan Brown',
      subtitulo: '',
      descricao: 'Após o assassinato de um curador no Louvre, Langdon e a criptóloga Sophie Neveu seguem pistas escondidas em obras de arte.',
      dataPublicacao: new Date(2003, 2, 18),
      capaUrl: 'livros/Robert2.jpg',
      idioma: 'Português',
      colecaoId: 18,
      status: 'disponível'
    },
    {
      id: 58,
      titulo: 'Robert Langdon: O Símbolo Perdido',
      autor: 'Dan Brown',
      subtitulo: '',
      descricao: 'Langdon é atraído a Washington por um mentor sequestrado e entra em uma corrida para decifrar segredos escondidos na capital americana.',
      dataPublicacao: new Date(2009, 8, 15),
      capaUrl: 'livros/Robert3.jpg',
      idioma: 'Português',
      colecaoId: 18,
      status: 'disponível'
    },
    {
      id: 59,
      titulo: 'Arsène Lupin: Ladrão de Casaca',
      autor: 'Maurice Leblanc',
      subtitulo: '',
      descricao: 'Coletânea de aventuras do elegante ladrão Arsène Lupin, mestre dos disfarces que desafia a polícia de Paris.',
      dataPublicacao: new Date(1907, 5, 1),
      capaUrl: 'livros/Lupin.jpg',
      idioma: 'Português',
      colecaoId: 19,
      status: 'disponível'
    },
    {
      id: 60,
      titulo: 'Arsène Lupin contra Herlock Sholmes',
      autor: 'Maurice Leblanc',
      subtitulo: '',
      descricao: 'O famoso detetive inglês Herlock Sholmes é chamado para capturar Lupin, em um duelo de inteligência entre os dois.',
      dataPublicacao: new Date(1908, 5, 1),
      capaUrl: 'livros/Lupin2.jpg',
      idioma: 'Português',
      colecaoId: 19,
      status: 'disponível'
    },
    {
      id: 61,
      titulo: 'Arsène Lupin: A Agulha Oca',
      autor: 'Maurice Leblanc',
      subtitulo: '',
      descricao: 'Lupin investiga um segredo ligado a uma agulha de pedra na Normandia e a um tesouro dos reis da França.',
      dataPublicacao: new Date(1909, 10, 1),
      capaUrl: 'livros/Lupin3.jpg',
      idioma: 'Português',
      colecaoId: 19,
      status: 'disponível'
    },
    {
      id: 62,
      titulo: 'Millennium: Os Homens que Não Amavam as Mulheres',
      autor: 'Stieg Larsson',
      subtitulo: '',
      descricao: 'O jornalista Mikael Blomkvist e a hacker Lisbeth Salander investigam o desaparecimento de uma jovem da rica família Vanger.',
      dataPublicacao: new Date(2005, 7, 1),
      capaUrl: 'livros/Millennium.jpg',
      idioma: 'Português',
      colecaoId: 20,
      status: 'disponível'
    },
    {
      id: 63,
      titulo: 'Millennium: A Menina que Brincava com Fogo',
      autor: 'Stieg Larsson',
      subtitulo: '',
      descricao: 'Lisbeth Salander é acusada de assassinatos e Blomkvist tenta provar sua inocência enquanto segredos do passado dela vêm à tona.',
      dataPublicacao: new Date(2006, 10, 1),
      capaUrl: 'livros/Millennium2.jpg',
      idioma: 'Português',
      colecaoId: 20,
      status: 'disponível'
    },
    {
      id: 64,
      titulo: 'Millennium: A Rainha do Castelo de Ar',
      autor: 'Stieg Larsson',
      subtitulo: '',
      descricao: 'Lisbeth luta por sua vida e por sua liberdade enquanto Blomkvist e a equipe da revista expõem uma conspiração no governo.',
      dataPublicacao: new Date(2007, 4, 1),
      capaUrl: 'livros/Millennium3.jpg',
      idioma: 'Português',
      colecaoId: 20,
      status: 'disponível'
    }
  ];

  buscarPorId(id: number): Livro | undefined {
    return this.livros.find(livro => livro.id === id);
  }

  listar(): readonly Livro[] {
    return this.livros;
  }

  listarPorColecao(colecaoId: number): readonly Livro[] {
    return this.livros.filter(livro => livro.colecaoId === colecaoId);
  }

}